### ISSUE TITLE
Sega Saturn reference DAT file?

### ISSUE THREAD

**Issue by kwyxz** [libretro-thumbnails/Sega_-_Saturn#1]
Hello folks,

I was working on adding thumbs for the Sega Saturn today and quickly realized there was a naming discrepancy between some database files, for example with the US version of Albert Odyssey :

```
metadat/redump/Sega - Saturn.dat:	name "Albert Odyssey - Legend of Eldean (USA)"
metadat/libretro-dats/Sega - Saturn.dat:	name "Albert Odyssey - Legend of Eldean (United States)"
```

It seems like currently the thumbnails are following the redump/ dat syntax, but wouldn't it make sense to have them follow the libretro-dats/ syntax? Thanks for letting me know!

**Comment by RobLoach** [comment]
Albert Odyssey - Legend of Eldean (USA) is what you want. There's https://github.com/robloach/libretro-thumbnails-check that will go through a check for you. Looks like it could use an update though.

**Comment by RobLoach** [comment]
That (United States) is probably from TOSEC or something. I really am conflicted on that set. Either way, use (USA) instead. Made an issue to force a rename during the cleaning of the entry names.

**Comment by kwyxz** [comment]
Sounds good, will do. Thanks!
